# -*- coding: utf-8 -*-
"""ocr_handwritting_train_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CAvN2zGpfzPT8u6R0kNS129A_OSj8n9c
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip -q datasets-20241108T030323Z-001.zip

pip install paddlepaddle-gpu==2.5.2

pip install "paddleocr>=2.0.1" # Recommend to use version 2.0.1+

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/PaddleOCR

!git clone https://github.com/thigiacmaytinh/PaddleOCR-Vietnamese.git

!git clone https://github.com/PaddlePaddle/PaddleOCR.git

# Commented out IPython magic to ensure Python compatibility.
# %cd  /content/drive/MyDrive/PaddleOCR-Vietnamese

pip install -r requirements.txt

!pwd



from google.colab import drive
drive.mount('/content/drive')

!python tools/train.py -c ./configs/det/SAST.yml

!pip list

!python tools/train.py -c ./configs/det/SAST.yml \
                       -o Global.checkpoints=./output/SAST/iter_epoch_1

!unzip /content/drive/MyDrive/PaddleOCR-Vietnamese/newdatasets.zip -d /content/drive/MyDrive/PaddleOCR-Vietnamese/newdatasets

!python tools/train.py -c ./configs/det/det_r50_vd_sast_icdar15.yml -o \
    Global.checkpoints=./output/sast_r50_vd_ic15/iter_epoch_300 \
    Optimizer.base_lr=0.0001

#evaluation model detection
!python tools/eval.py  -c ./configs/det/det_r50_vd_sast_icdar15.yml \
                      -o Global.checkpoints_model=./output/sast_r50_vd_ic15/latest

# Convert mô hình dectection
!python tools/export_model.py -c ./configs/det/det_r50_vd_sast_icdar15.yml  \
                             -o Global.pretrained_model=./output/sast_r50_vd_ic15/latest \
                                Global.save_inference_dir=./inference/det_r50_vd_sast_icdar15

# Predict detection
!python tools/infer/predict_det.py  --det_algorithm="SAST" \
                                   --use_gpu=False \
                                   --det_model_dir="./inference/det_r50_vd_sast_icdar15"  \
                                   --image_dir="/content/drive/MyDrive/PaddleOCR/inference_results/unnamed.png"

import os
import numpy as np
from tqdm import tqdm
import pandas as pd
import json
import glob

root_path = glob.glob('./vietnamese_original/vietnamese/labels/*')

train_label = open("train_label.txt","w")
test_label = open("test_label.txt","w")
useen_label = open("useen_label.txt","w")
for file in root_path:
    with open(file) as f:
      content = f.readlines()
      f.close()
    content = [x.strip() for x in content]
    text = []
    for i in content:
      label = {}
      i = i.split(',',8)
      label['transcription'] = i[-1]
      label['points'] = [[i[0],i[1]],[i[2],i[3]], [i[4],i[5]],[i[6],i[7]]]
      text.append(label)

    content = []
    text = json.dumps(text, ensure_ascii=False)

    img_name = os.path.basename(file).split('.')[0].split('_')[1]
    int_img = int(img_name)
    img_name = 'im' + "{:04n}".format(int(img_name)) + '.jpg'
    if int_img > 1500:
      useen_label.write( img_name+ '\t'+f'{text}' + '\n')
    elif int_img > 1200:
      test_label.write( img_name+ '\t'+f'{text}' + '\n')
    else:
      train_label.write( img_name+ '\t'+f'{text}' + '\n')

from PIL import Image
import os

# Đường dẫn đến thư mục đầu vào và đầu ra
input_folder = '/content/drive/MyDrive/PaddleOCR/datasets/test'
output_folder = '/content/drive/MyDrive/PaddleOCR/inference_results'
new_size = (512, 512)  # Kích thước mong muốn

# Tạo thư mục đầu ra nếu chưa tồn tại
os.makedirs(output_folder, exist_ok=True)

# Thay đổi kích thước ảnh
for filename in os.listdir(input_folder):
    if filename.endswith('.jpg') or filename.endswith('.png'):  # Lọc các file ảnh
        img_path = os.path.join(input_folder, filename)
        img = Image.open(img_path)  # Mở ảnh
        img_resized = img.resize(new_size)  # Thay đổi kích thước ảnh
        output_path = os.path.join(output_folder, filename)
        img_resized.save(output_path)  # Lưu ảnh đã thay đổi kích thước

print("Đã thay đổi kích thước ảnh thành công!")